# Generated by Django 3.1.5 on 2021-01-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='neighborhood_data',
            fields=[
                ('zipCode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('crimeIndex', models.FloatField()),
                ('crimeCount', models.FloatField()),
                ('crimeRatio', models.FloatField()),
                ('neighborhood', models.CharField(max_length=20)),
                ('quadrant', models.CharField(max_length=10)),
                ('avgRent', models.FloatField()),
                ('rentLow', models.FloatField()),
                ('rentHigh', models.FloatField()),
                ('walkIndex', models.FloatField()),
                ('violenceIndex', models.FloatField()),
                ('crimeTime', models.CharField(max_length=2)),
                ('avgHomeValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='housing_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('projectName', models.CharField(max_length=100)),
                ('management', models.CharField(max_length=100)),
                ('xCoord', models.FloatField()),
                ('yCoord', models.FloatField()),
                ('neighborhood', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('contactPhone', models.CharField(max_length=12)),
                ('totalUnits', models.IntegerField()),
                ('singleRoom', models.IntegerField()),
                ('studio', models.IntegerField()),
                ('oneBedroom', models.IntegerField()),
                ('twoBedroom', models.IntegerField()),
                ('threeBedroom', models.IntegerField()),
                ('fourBedroom', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('zipCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_app.neighborhood_data')),
            ],
            options={
                'ordering': ['projectName'],
            },
        ),
    ]
