# Generated by Django 3.1.5 on 2021-01-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood_data',
            name='safetyRank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
