# Generated by Django 3.1.5 on 2021-01-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing_data',
            name='fourBedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='oneBedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='singleRoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='studio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='threeBedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='totalUnits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='twoBedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='xCoord',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='yCoord',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
