# Generated by Django 3.1.5 on 2021-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0003_auto_20210115_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing_data',
            name='created',
        ),
        migrations.AlterField(
            model_name='housing_data',
            name='updated',
            field=models.DateField(),
        ),
    ]
