# Generated by Django 3.1.5 on 2021-01-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0004_auto_20210116_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood_data',
            name='avgHomeValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='avgRent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='crimeTime',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='quadrant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='rentHigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='rentLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='violenceIndex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood_data',
            name='walkIndex',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
